[project]
name = "scamSi"
version = "0.0.1"
authors = [
  { name="Jakub Trajhan", email="trajhja24@sps-prosek.cz" },
]

description = "game or whatever"
readme = "README.md"
requires-python = ">=3.11"

dependencies = [
    "pygame-ce"
]

classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
]


[project.scripts]
scamSi = "scamSi.main:main"


[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
where = ["src"]
package-dir = {"" = "src"}